version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: matchodds-db
    environment:
      POSTGRES_DB: matchodds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '55432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: matchodds-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/matchodds
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: 'true'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - '8080:8080'
    restart: on-failure
    # Wait for db to be ready before starting the app
    entrypoint:
      [
        'sh',
        '-c',
        'until pg_isready -h db -p 5432; do sleep 1; done; exec java -jar app.jar',
      ]

volumes:
  db_data:
